<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hh_ckeditor_custom"
 *
 * Auto generated by Extension Builder 2017-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['hh_ckeditor_custom'] = [
    'title' => 'Simple Ext for customize the ck_editor',
    'description' => 'RTE ck_editor custom config with example data',
    'category' => 'be',
    'author' => 'Christian Hackl',
    'author_email' => 'web@hauer-heinrich.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.61',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.1-11.5.99',
            'rte_ckeditor' => '',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
