# Load default processing options
imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

# Add configuration for the editor
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config
# English tutorials:
# https://typo3worx.eu/2017/02/configure-ckeditor-in-typo3/
# German Tutorials:
# https://www.clickstorm.de/blog/der-neue-typo3-rte-ckeditor/
# https://www.thomaskieslich.de/blog/127-typo3-8x-ckeditor-konfigurieren/

editor:

  config:

    contentsCss: ["EXT:rte_ckeditor/Resources/Public/Css/contents.css", "fileadmin/hh_ckeditor_custom/Resources/Public/Css/custom_ckeditor.css"]

    # For inline stil:
    stylesSet: [{ "name": "color1", "element": "span", "attributes": {"class": "color1"} }, { "name": "color2", "element": "span", "attributes": {"class": "color2"} }]

    # format tags:
    format_tags: "p;pre"

    # Plugin colorbutton config:
    # allow only your colors:
    # colorButton_colors: 'eeeeee,074e7c'
    # colorButton_foreStyle: { element: 'span', class: { 'color': '#(color)' } }
    # colorButton_enableAutomatic: false

    # RTE Backend Color:
    # uiColor: 074e7c

    # RTE Backend Button List
    # - "/" = new line
    toolbarGroups:
      - { name: document, groups: [ mode, document, doctools ] }
      - { name: clipboard, groups: [ clipboard, undo ] }
      - { name: editing, groups: [ find, selection, spellchecker, editing ] }
      - { name: forms, groups: [ forms ] }
      - { name: basicstyles, groups: [ basicstyles, cleanup ] }
      - "/"
      - { name: paragraph, groups: [ list, indent, blocks, align, bidi, paragraph ] }
      - { name: links, groups: [ links ] }
      - { name: insert, groups: [ insert ] }
      - { name: styles, groups: [ styles ] }
      - { name: colors, groups: [ colors ] }
      - { name: tools, groups: [ tools ] }
      - { name: others, groups: [ others ] }
      - { name: about, groups: [ about ] }

    justifyClasses:
      - text-left
      - text-center
      - text-right
      - text-justify

    extraPlugins:
      - justify
      - specialchar
      - showblocks
      - colorbutton
      - link

    removePlugins:
      - image

    removeButtons:
      - Save
      - NewPage
      - Preview
      - Print
      - Form
      - Checkbox
      - Radio
      - TextField
      - Textarea
      - Select
      - Button
      - ImageButton
      - HiddenField
      - CreateDiv
      - Image
      - Flash
      - Table
      - Smiley
      - Iframe
      - About

    extraAllowedContent:
      - a[!href,document-href,tel]

  # external Plugin e. g.:
  # externalPlugins:
    # dialogadvtab: { resource: "EXT:extensionName/Resources/Public/JavaScript/RTE_Plugins/dialogadvtab/plugin.js" }
